name: ci

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: |
          go mod tidy
      - name: Testing
        run: |
          go test ./...
      - name: Generate binary
        run: |
          make build
      - name: Upload binary
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./bin/go-installer
          make_latest: true

