name: ci

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      - name: Install dependencies
        run: |
          go mod tidy
      - name: Testing
        run: |
          go test ./...